In [1]:
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
import pandas as pd
import csv

In [2]:
dataset_test = pd.read_csv(r'C:\datasets\pima-indians_diabetes.csv')
print(type(dataset_test.values))

line = csv.reader(open(r'C:\datasets\pima-indians_diabetes.csv'))
dataset_test2 = list(line)
print(type(dataset_test2))

dataset = datasets.load_iris()
print(type(dataset))


<class 'numpy.ndarray'>
<class 'list'>
<class 'sklearn.utils.Bunch'>


In [29]:
model = GaussianNB()
model.fit(dataset.data, dataset.target)

expected = dataset.target
predicted = model.predict(dataset.data)

In [33]:
print(metrics.classification_report(expected, predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.94      0.94        50
           2       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150



In [34]:
print(metrics.confusion_matrix(expected, predicted))

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]
